### PR TITLE
can filter with Buffer chan

### LINKED ISSUE #236: sub: filter by binary chan prefix?
I'm transfering all messages between nanomsg nodes in binary format. But filtering with `chan` option do not work:
```js
let chan = ["\x95"] // tried Buffer.from([0x95]) too
let sub = socket('sub', {chan})
// sub doesn't receive messages starting with [0x95, ...]
```
Look like because chan converted to utf-8 string before passing to `nn_setsockopt`
    https://github.com/nickdesaulniers/node-nanomsg/blob/428455eae354c44a6ef77a7d24ab82b3757bfc60/src/node_nanomsg.cc#L59

### PR DESCRIPTION
**Pull request by farwayer**
fix #236

### CODE REVIEW

File: src/node_nanomsg.cc [hunk 1]
```diff
@@ -56,10 +56,16 @@ NAN_METHOD(Chan) {
...
-  info.GetReturnValue().Set(Nan::New<v8::Number>(
+  if (node::Buffer::HasInstance(info[2])) {
+    info.GetReturnValue().Set(Nan::New<v8::Number>(nn_setsockopt(
+        s, level, option, node::Buffer::Data(info[2]),
+        node::Buffer::Length(info[2]))));
+  } else {
+    Nan::Utf8String str(info[2]);
+    info.GetReturnValue().Set(Nan::New<v8::Number>(
         nn_setsockopt(s, level, option, *str, str.length())));
+    }
```
Comment (nickdesaulniers) [inline src/node_nanomsg.cc:68]: There's a fair amount of duplication on either side of that condition.  Perhaps you can call `nn_setsockopt` two different ways in either branch, but then have the common tail construct the v8::Number and call Set after?

**Review by nickdesaulniers — COMMENTED** [review]
Thanks for the patch!

File: src/node_nanomsg.cc (hunk 1 above)
Comment (farwayer) [reply src/node_nanomsg.cc]: I used the same code style as in Send method but sure!

**Review by nickdesaulniers — APPROVED** [review]
